name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug Secrets
        run: echo "${{ secrets.EC2_SSH_KEY }}" | tr '\n' ' ' | cut -c1-100
      - name: Fix SSH Key Permissions
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd trading-app
            git pull origin main
            docker stop fastapi-orders || true
            docker rm fastapi-orders || true
            docker build -t fastapi-orders .
            docker run -d -p 8000:8000 fastapi-orders
