name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH Key and Config
        run: |
          mkdir -p ~/.ssh
          # Save the SSH key
          echo "${{ secrets.EC2_SSH_KEY }}" | tr ' ' '\n' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Configure SSH to bypass host key verification
          echo "Host ${{ secrets.EC2_HOST }}
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd trading-app
            git pull origin main
            docker stop fastapi-orders || true
            docker rm fastapi-orders || true
            docker build -t fastapi-orders .
            docker run -d -p 8000:8000 fastapi-orders
