name: Deploy to EC2 via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy trading-app folder to EC2
        uses: garygrossgarten/github-action-scp@release
        with:
          local: trading-app
          remote: /home/ec2-user/trading-app
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          privateKey: ${{ secrets.EC2_SSH_KEY }}
          recursive: true
