name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request_target: # Ensures secrets work in PRs safely
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Ensures secrets are available

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr ' ' '\n' > private_key.pem
          chmod 600 private_key.pem
          echo "Key Length: $(wc -c < private_key.pem)"  # Debug

      - name: Add SSH Host Key (Bypass Verification)
        run: |
          mkdir -p ~/.ssh
          echo "Host ${{ secrets.EC2_HOST }}
                StrictHostKeyChecking no
                UserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Debug SSH Connection
        run: ssh -vvv -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.EC2_HOST }}

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd trading-app
            git pull origin main
            docker stop fastapi-orders || true
            docker rm fastapi-orders || true
            docker build -t fastapi-orders .
            docker run -d -p 8000:8000 fastapi-orders
